---
title: "Curso Machine Learning UEMA 2025"
author: "Thiago S. F. Silva"
format: html
---

[Programa do curso](handouts/informacoes_pre_curso.pdf)

## Material do Curso:

### Aula 1 - Introdução (09/12/2025)

[Slides Aula 1](slides/aula_1.pdf)

### Aula 2 - Gerenciamento de Dados (10 e 11/12/2025)

[Slides Aula 2](slides/aula_2.pdf)

### Aula 3 - Visualização de dados (12/12/2025)

[Slides Aula 3](slides/aula_3.pdf)

### Aula 4 - Introdução ao Machine Learning (15 e 16/12/2025)

[Slides Aula 4](slides/aula_4.pdf)

### Aula 5 - Geprocessamento e machine learning

[Slides Aula 5](slides/Aula_5.pdf)

[Poster explicativo CRS](figs/CRS_poster.png)

### Datasets e scripts criados durante o curso 

| Datasets | Scripts |
|--------------------|----------------------------------|
|[Exemplo de metadados](data/exemplo_metadado.txt) | [`1_carrega_dados.R`](demos/1_carrega_dados.R) |
|[Planilha do Capeta](data/planilha_do_capeta.xlsx)| [`2_explorando_tidyverse.R`](demos/2_explorando_tidyverse.R) |
|[Plot Florestal (xlsx)](data/plot_florestal.xlsx) | [`3_explorando_ggplot2.R`](demos/3_explorando_ggplot2.R) |
|[Turbidez (csv)](data/turbidez.csv)               | [`4_preprocessamento_turbidez.R`](demos/4_preprocessamento_turbidez.R) |
|[Voos (parquet)](data/flights-1m.parquet)         | [`5_exemplo_RF.R`](demos/5_exemplo_RF.R) |
|[Macrófitas (csv)](data/rich_env_jun.csv)         | [`6_modelando_tidymodels.R`](demos/6_modelando_tidymodels.R) |
|[imagem_composta_CBERS](data/imagem_composta_CBERS.tif) | [`7_explorando_terra_e_sf.R`](demos/7_explorando_terra_e_sf) 
|[amostras_treinamento](data/amostras.gpkg)        | [`8_classificando_imagens.R`](demos/7_classificando_imagens.R)      |

